#!/data/data/com.termux/files/usr/bin/bash
# SuperClaw Termux:Boot Setup
# This script sets up SuperClaw to auto-start when Android boots

set -e

SUPERCLAW_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOT_DIR="$HOME/.termux/boot"
BOOT_SCRIPT="$BOOT_DIR/start-superclaw.sh"

echo "🦀 SuperClaw Termux:Boot Setup"
echo "================================"

# Check if we're in Termux
if [ -z "$TERMUX_VERSION" ] && [ ! -d "/data/data/com.termux" ]; then
    echo "❌ This script must be run in Termux"
    exit 1
fi

# Check if Termux:Boot is installed
if [ ! -d "/data/data/com.termux.boot" ]; then
    echo "⚠️  Termux:Boot app not detected."
    echo "   Please install it from F-Droid: https://f-droid.org/packages/com.termux.boot/"
    echo "   Then run this script again."
    echo ""
    echo "   Continuing setup anyway..."
fi

# Create boot directory
mkdir -p "$BOOT_DIR"
echo "✅ Created boot directory: $BOOT_DIR"

# Build the SuperClaw binary if needed
if [ ! -f "$SUPERCLAW_DIR/dist/index.js" ]; then
    echo "📦 Building SuperClaw..."
    cd "$SUPERCLAW_DIR"
    pnpm build
fi

# Write boot script
cat > "$BOOT_SCRIPT" << EOF
#!/data/data/com.termux/files/usr/bin/bash
# SuperClaw auto-start on Android boot
# Generated by termux-boot-setup.sh

# Acquire wake lock to prevent CPU sleep
termux-wake-lock

# Wait for network
sleep 10

# Start SuperClaw
cd $SUPERCLAW_DIR
export NODE_ENV=production
export PATH="\$PATH:/data/data/com.termux/files/usr/bin"

node dist/index.js >> "\$HOME/superclaw-boot.log" 2>&1 &

echo "SuperClaw started at \$(date)" >> "\$HOME/superclaw-boot.log"
EOF

chmod +x "$BOOT_SCRIPT"
echo "✅ Boot script created: $BOOT_SCRIPT"

echo ""
echo "🎉 Termux:Boot setup complete!"
echo ""
echo "Next steps:"
echo "  1. Install Termux:Boot from F-Droid (if not already installed)"
echo "  2. Open Termux:Boot app once to activate it"
echo "  3. SuperClaw will now auto-start when your Android device boots"
echo ""
echo "To check boot log: cat ~/superclaw-boot.log"
echo "To remove auto-start: rm $BOOT_SCRIPT"
