import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { Tool, ToolResult } from '../gateway/types';
import { logger } from '../logger';

type DaemonAction =
  | 'install_termux_boot'
  | 'remove_termux_boot'
  | 'install_systemd'
  | 'remove_systemd'
  | 'status'
  | 'install_pm2'
  | 'pm2_status';

export class DaemonManagerTool implements Tool {
  name = 'daemon_manager';
  description =
    'Manage SuperClaw as a background daemon/service. Supports Termux:Boot (Android auto-start on reboot), systemd user service (Linux VPS), and PM2 process manager. Actions: install_termux_boot, remove_termux_boot, install_systemd, remove_systemd, status, install_pm2, pm2_status';
  parameters = {
    type: 'object',
    properties: {
      action: {
        type: 'string',
        enum: [
          'install_termux_boot',
          'remove_termux_boot',
          'install_systemd',
          'remove_systemd',
          'status',
          'install_pm2',
          'pm2_status',
        ],
        description:
          'Action to perform: install_termux_boot (Android auto-start), remove_termux_boot, install_systemd (Linux user service), remove_systemd, status (check all daemons), install_pm2, pm2_status',
      },
      superclaw_path: {
        type: 'string',
        description:
          'Path to SuperClaw installation directory. Defaults to current working directory.',
      },
    },
    required: ['action'],
  };

  async execute(params: { action: DaemonAction; superclaw_path?: string }): Promise<ToolResult> {
    const { action, superclaw_path } = params;
    const superclawDir = superclaw_path || process.cwd();

    logger.info(`DaemonManagerTool: action=${action}, path=${superclawDir}`);

    try {
      switch (action) {
        case 'install_termux_boot':
          return this.installTermuxBoot(superclawDir);
        case 'remove_termux_boot':
          return this.removeTermuxBoot();
        case 'install_systemd':
          return this.installSystemd(superclawDir);
        case 'remove_systemd':
          return this.removeSystemd(superclawDir);
        case 'status':
          return this.getStatus();
        case 'install_pm2':
          return this.installPm2(superclawDir);
        case 'pm2_status':
          return this.getPm2Status();
        default:
          return { success: false, error: `Unknown action: ${action}` };
      }
    } catch (error: any) {
      logger.error('DaemonManagerTool error', { error: error.message });
      return { success: false, error: error.message };
    }
  }

  // ─── Termux:Boot ────────────────────────────────────────────────────────────

  private installTermuxBoot(superclawDir: string): ToolResult {
    const home = process.env.HOME || '/data/data/com.termux/files/home';
    const bootDir = path.join(home, '.termux', 'boot');
    const bootScript = path.join(bootDir, 'start-superclaw.sh');

    // Check if Termux:Boot is available
    const termuxBootAppExists = fs.existsSync('/data/data/com.termux.boot');
    const bootDirExists = fs.existsSync(bootDir);
    const isTermux =
      !!process.env.TERMUX_VERSION || fs.existsSync('/data/data/com.termux');

    if (!isTermux && !bootDirExists) {
      return {
        success: false,
        error:
          'Termux environment not detected. This action is only supported on Android with Termux installed.',
      };
    }

    // Create boot directory if it doesn't exist
    try {
      fs.mkdirSync(bootDir, { recursive: true });
    } catch (error: any) {
      return { success: false, error: `Failed to create boot directory: ${error.message}` };
    }

    // Write the boot script
    const scriptContent = [
      '#!/data/data/com.termux/files/usr/bin/bash',
      '# SuperClaw auto-start on Android boot',
      '# Generated by DaemonManagerTool',
      '',
      '# Acquire wake lock to prevent CPU sleep',
      'termux-wake-lock',
      '',
      '# Wait for network to be available',
      'sleep 10',
      '',
      '# Start SuperClaw',
      `cd ${superclawDir}`,
      'export NODE_ENV=production',
      'export PATH="$PATH:/data/data/com.termux/files/usr/bin"',
      '',
      `node dist/index.js >> "$HOME/superclaw-boot.log" 2>&1 &`,
      '',
      `echo "SuperClaw started at $(date)" >> "$HOME/superclaw-boot.log"`,
    ].join('\n');

    try {
      fs.writeFileSync(bootScript, scriptContent, { encoding: 'utf8' });
    } catch (error: any) {
      return { success: false, error: `Failed to write boot script: ${error.message}` };
    }

    // Make it executable
    try {
      execSync(`chmod +x "${bootScript}"`, { encoding: 'utf8' });
    } catch (error: any) {
      return { success: false, error: `Failed to make boot script executable: ${error.message}` };
    }

    const warnings: string[] = [];
    if (!termuxBootAppExists) {
      warnings.push(
        'Termux:Boot app not detected. Install it from F-Droid: https://f-droid.org/packages/com.termux.boot/',
      );
      warnings.push('After installing, open the Termux:Boot app once to activate it.');
    }

    return {
      success: true,
      data: {
        bootScript,
        superclawDir,
        termuxBootAppInstalled: termuxBootAppExists,
        warnings,
        instructions: [
          `Boot script created at: ${bootScript}`,
          'SuperClaw will now auto-start when your Android device boots.',
          ...(warnings.length > 0 ? ['', '⚠️  Action required:', ...warnings] : []),
          '',
          'Useful commands:',
          `  View boot log:    cat ~/superclaw-boot.log`,
          `  Remove auto-start: rm "${bootScript}"`,
        ].join('\n'),
      },
    };
  }

  private removeTermuxBoot(): ToolResult {
    const home = process.env.HOME || '/data/data/com.termux/files/home';
    const bootScript = path.join(home, '.termux', 'boot', 'start-superclaw.sh');

    if (!fs.existsSync(bootScript)) {
      return {
        success: true,
        data: { message: `Boot script not found at ${bootScript} — nothing to remove.` },
      };
    }

    try {
      fs.unlinkSync(bootScript);
      return {
        success: true,
        data: { message: `Removed Termux:Boot script: ${bootScript}` },
      };
    } catch (error: any) {
      return { success: false, error: `Failed to remove boot script: ${error.message}` };
    }
  }

  // ─── systemd user service ────────────────────────────────────────────────────

  private installSystemd(superclawDir: string): ToolResult {
    const home = process.env.HOME || '';
    if (!home) {
      return { success: false, error: 'HOME environment variable is not set.' };
    }

    const systemdDir = path.join(home, '.config', 'systemd', 'user');
    const serviceFile = path.join(systemdDir, 'superclaw.service');

    // Resolve node binary path
    let nodePath = '/usr/bin/node';
    try {
      nodePath = execSync('which node', { encoding: 'utf8' }).trim() || nodePath;
    } catch {
      // fall back to /usr/bin/node
    }

    // Ensure logs directory exists
    const logsDir = path.join(superclawDir, 'logs');
    try {
      fs.mkdirSync(logsDir, { recursive: true });
    } catch {
      // ignore if already exists
    }

    // Create systemd user directory
    try {
      fs.mkdirSync(systemdDir, { recursive: true });
    } catch (error: any) {
      return { success: false, error: `Failed to create systemd directory: ${error.message}` };
    }

    // Write service file
    const serviceContent = [
      '[Unit]',
      'Description=SuperClaw AI Agent',
      'After=network.target',
      '',
      '[Service]',
      'Type=simple',
      `WorkingDirectory=${superclawDir}`,
      `ExecStart=${nodePath} ${superclawDir}/dist/index.js`,
      'Restart=on-failure',
      'RestartSec=10',
      `StandardOutput=append:${superclawDir}/logs/app.log`,
      `StandardError=append:${superclawDir}/logs/error.log`,
      'Environment=NODE_ENV=production',
      '',
      '[Install]',
      'WantedBy=default.target',
    ].join('\n');

    try {
      fs.writeFileSync(serviceFile, serviceContent, { encoding: 'utf8' });
    } catch (error: any) {
      return { success: false, error: `Failed to write service file: ${error.message}` };
    }

    // Enable and start the service
    const results: Record<string, string> = {};
    const errors: string[] = [];

    for (const cmd of [
      'systemctl --user daemon-reload',
      'systemctl --user enable superclaw',
      'systemctl --user start superclaw',
    ]) {
      try {
        results[cmd] = execSync(cmd, { encoding: 'utf8' }).trim();
      } catch (error: any) {
        const msg = error.stderr?.trim() || error.message;
        errors.push(`${cmd}: ${msg}`);
        results[cmd] = `ERROR: ${msg}`;
      }
    }

    // Get final status
    let serviceStatus = 'unknown';
    try {
      serviceStatus = execSync('systemctl --user is-active superclaw', {
        encoding: 'utf8',
      }).trim();
    } catch (error: any) {
      serviceStatus = error.stdout?.trim() || 'failed';
    }

    return {
      success: errors.length === 0,
      data: {
        serviceFile,
        nodePath,
        superclawDir,
        commandResults: results,
        serviceStatus,
        errors: errors.length > 0 ? errors : undefined,
        instructions: [
          `Service file created: ${serviceFile}`,
          `Service status: ${serviceStatus}`,
          '',
          'Useful commands:',
          '  Status:  systemctl --user status superclaw',
          '  Logs:    journalctl --user -u superclaw -f',
          '  Stop:    systemctl --user stop superclaw',
          '  Restart: systemctl --user restart superclaw',
        ].join('\n'),
      },
      error: errors.length > 0 ? errors.join('; ') : undefined,
    };
  }

  private removeSystemd(superclawDir: string): ToolResult {
    const home = process.env.HOME || '';
    const serviceFile = path.join(home, '.config', 'systemd', 'user', 'superclaw.service');

    const results: Record<string, string> = {};
    const errors: string[] = [];

    // Stop and disable first
    for (const cmd of [
      'systemctl --user stop superclaw',
      'systemctl --user disable superclaw',
    ]) {
      try {
        results[cmd] = execSync(cmd, { encoding: 'utf8' }).trim();
      } catch (error: any) {
        const msg = error.stderr?.trim() || error.message;
        // Not a fatal error if service wasn't running
        results[cmd] = `WARNING: ${msg}`;
      }
    }

    // Remove service file
    if (fs.existsSync(serviceFile)) {
      try {
        fs.unlinkSync(serviceFile);
        results['remove_file'] = `Removed ${serviceFile}`;
      } catch (error: any) {
        errors.push(`Failed to remove service file: ${error.message}`);
      }
    } else {
      results['remove_file'] = `Service file not found at ${serviceFile} — skipped.`;
    }

    // Reload daemon
    try {
      execSync('systemctl --user daemon-reload', { encoding: 'utf8' });
      results['daemon-reload'] = 'OK';
    } catch (error: any) {
      results['daemon-reload'] = `WARNING: ${error.message}`;
    }

    return {
      success: errors.length === 0,
      data: { commandResults: results, serviceFile },
      error: errors.length > 0 ? errors.join('; ') : undefined,
    };
  }

  // ─── Status ─────────────────────────────────────────────────────────────────

  private getStatus(): ToolResult {
    const home = process.env.HOME || '';
    const status: Record<string, any> = {};

    // Termux:Boot status
    const bootScript = path.join(home, '.termux', 'boot', 'start-superclaw.sh');
    status.termuxBoot = {
      scriptExists: fs.existsSync(bootScript),
      scriptPath: bootScript,
      termuxBootAppInstalled: fs.existsSync('/data/data/com.termux.boot'),
    };

    // systemd status
    let systemdActive = 'not_available';
    try {
      systemdActive = execSync('systemctl --user is-active superclaw', {
        encoding: 'utf8',
      }).trim();
    } catch (error: any) {
      systemdActive = error.stdout?.trim() || 'inactive';
    }

    const serviceFile = path.join(home, '.config', 'systemd', 'user', 'superclaw.service');
    status.systemd = {
      isActive: systemdActive,
      serviceFileExists: fs.existsSync(serviceFile),
      serviceFilePath: serviceFile,
    };

    // PM2 status
    let pm2Output = '';
    let pm2Available = false;
    try {
      pm2Output = execSync('pm2 describe superclaw --no-color', { encoding: 'utf8' }).trim();
      pm2Available = true;
    } catch (error: any) {
      pm2Output = error.stdout?.trim() || error.message;
      pm2Available = !error.message.includes('command not found');
    }

    status.pm2 = {
      available: pm2Available,
      output: pm2Output,
    };

    return { success: true, data: status };
  }

  // ─── PM2 ────────────────────────────────────────────────────────────────────

  private installPm2(superclawDir: string): ToolResult {
    const results: Record<string, string> = {};
    const errors: string[] = [];

    // Install PM2 globally
    try {
      results['npm install -g pm2'] = execSync('npm install -g pm2', {
        encoding: 'utf8',
        cwd: superclawDir,
      }).trim();
    } catch (error: any) {
      const msg = error.stderr?.trim() || error.message;
      errors.push(`npm install -g pm2: ${msg}`);
      results['npm install -g pm2'] = `ERROR: ${msg}`;
    }

    // Start with ecosystem config
    const ecosystemPath = path.join(superclawDir, 'ecosystem.config.js');
    const startCmd = fs.existsSync(ecosystemPath)
      ? `pm2 start "${ecosystemPath}" --env production`
      : `pm2 start "${superclawDir}/dist/index.js" --name superclaw`;

    try {
      results[startCmd] = execSync(startCmd, { encoding: 'utf8', cwd: superclawDir }).trim();
    } catch (error: any) {
      const msg = error.stderr?.trim() || error.message;
      errors.push(`${startCmd}: ${msg}`);
      results[startCmd] = `ERROR: ${msg}`;
    }

    // Save PM2 process list
    try {
      results['pm2 save'] = execSync('pm2 save', { encoding: 'utf8' }).trim();
    } catch (error: any) {
      results['pm2 save'] = `WARNING: ${error.message}`;
    }

    // Generate startup script
    try {
      results['pm2 startup'] = execSync('pm2 startup', { encoding: 'utf8' }).trim();
    } catch (error: any) {
      results['pm2 startup'] = `WARNING: ${error.message}`;
    }

    return {
      success: errors.length === 0,
      data: {
        commandResults: results,
        instructions: [
          'PM2 installation complete.',
          '',
          'Useful commands:',
          '  Status:  pm2 status',
          '  Logs:    pm2 logs superclaw',
          '  Stop:    pm2 stop superclaw',
          '  Restart: pm2 restart superclaw',
          '  Monitor: pm2 monit',
        ].join('\n'),
      },
      error: errors.length > 0 ? errors.join('; ') : undefined,
    };
  }

  private getPm2Status(): ToolResult {
    try {
      const output = execSync('pm2 describe superclaw --no-color', { encoding: 'utf8' }).trim();
      return { success: true, data: { output } };
    } catch (error: any) {
      const output = error.stdout?.trim() || '';
      const isNotFound = error.message.includes('command not found');
      return {
        success: !isNotFound,
        data: { output },
        error: isNotFound ? 'PM2 is not installed. Run install_pm2 action first.' : undefined,
      };
    }
  }
}

export const daemonManagerTool = new DaemonManagerTool();
export default daemonManagerTool;
